### ISSUE TITLE
@robertfchapman you're welcome, but you closed the pull request instead of merging it, so the problem is still there:

### ISSUE THREAD

**Issue by robertfchapman** [robertfchapman/MAX5481#2]
@robertfchapman you're welcome, but you closed the pull request instead of merging it, so the problem is still there:
https://github.com/robertfchapman/MAX5481/blob/master/Library.properties

_Originally posted by @per1234 in https://github.com/robertfchapman/MAX5481/issues/1#issuecomment-744108401_

@per1234, I apologize for closing the pull request, I'm still a bit of a newbie when it comes to using github tools.  I'm getting better.  If you know how I can re-open the request and merge it I will.  Again, I thank you for your contribution and I would like for you to get credit for it.

**Comment by per1234** [comment]
Hi @robertfchapman. I really appreciate your courtesy. I'm not at all concerned with credit. My only desire was to make a small contribution to your project. I was only concerned that the issue had not been resolved. I'm just happy that the issue has been fixed.

Thanks for your contribution to the Arduino community!
Regards, Per

**Comment by robertfchapman** [comment]
@per12234, Thanks again.  Please do keep an eye on future projects (repos), any help is always welcomed.  And in the future, I'll make sure to do better with processing things within the github tools.
